### ISSUE TITLE
Single Badge View shows too many earners (false positives)

### ISSUE THREAD

**Issue by reneneee** [opencredit/badgeos#446]
Viewing a badge shows some users that have not earned the badge shown.

**Comment by reneneee** [comment]
Filed PR #447 to fix this.

**Comment by tw2113** [comment]
Hi @reneneee 
Thank you for your feedback and issue and PR.

From what I can tell, this is very similar, if not exactly the same issue as #213 for which I have a fix in place and ready for at 0e5297ebd26f8a55346cbe449dae33aefa18266c

To summarize the issue, there were cases where the achievement ID was returning users because it matched a different part of the meta data being stored, particularly timestamps. This is because of the "LIKE" searching in the query.

If your solution is working, by all means you can go ahead and stick with it, but I'm leaning more towards the solution I found above where I validate the achievements before returning the user. If you'd like to implement the same solution feel free to do that as well. I intend to have it be part of the next release when we get to that.
