### ISSUE TITLE
Get achievement post thumbnail with earned/unearned-distinction

### ISSUE THREAD

**Issue by scepbjoern** [opencredit/badgeos#479]
I'm trying to get thumbnails of certain badges in a content-template. This works with the following code (the essential function is badgeos_get_achievement_post_thumbnail):

```php
$posts = get_field('badges');

if( $posts ): ?>
	<?php foreach( $posts as $post): // variable must be called $post (IMPORTANT) ?>
		<?php setup_postdata($post); ?>
		<?php echo badgeos_get_achievement_post_thumbnail( $post->ID ); ?>
		<?php wp_reset_postdata(); // IMPORTANT - reset the $post object so the rest of the page works correctly ?>		
	<?php endforeach; ?>
<?php endif; ?>
```

However, what I wanted is to show earned badges like they are displayed now (coloured), but to show unearned badges greyed out. How can I achieve this?

**Comment by tw2113** [comment]
Hey @scepbjoern if you would be so kind, could you start a support thread over at https://wordpress.org/support/plugin/badgeos and we'll get you taken care of there. Since this isn't a bug report or an enhancement issue, our support forum is the more appropriate location to handle the question at hand.

Thank you.
