### ISSUE TITLE
Award publish trigger to post_author when a post is published, instead of current user

### ISSUE THREAD

**Issue by rastarr** [opencredit/badgeos#48]
I hope it's OK to log a bug issue on the 1.1 beta here.

I just tested the Publish Post on my localhost for a scheduled test post.
The badge wasn't awarded once the post went live - is this something that can be looked at?

**Comment by tw2113** [comment]
I'm not managing to create this one, to be honest. I wonder if it ended up getting fixed in the time between original issue and latest version.

If someone can recreate the issue of the current user getting the achievement instead of the post author, feel free to comment, but for now I'm going to close it.
