### ISSUE TITLE
Achievement image remains the default image of the achievement type even if one is configured on the achievement

### ISSUE THREAD

**Issue by agence-glanum** [opencredit/badgeos#484]
WordPress version : 4.2.2
BadgeOS plugin version : 1.4.6
BadgeOS LearnDash Add-On version : 1.0.0

Hello,

I have a problem with the update of achievement. I modified the achievement image in the post (PNG image or Credly) but the image displayed on the site remains one configured as the default image in the Achievement Types menu.

In the code, the badgeos_get_achievement_post_thumbnail function calls the get_the_post_thumbnail native function that returns an empty string. The html code of the image is correct before the call of the end_fetch_post_thumbnail_html action (l. 132 of the attached image), which replaces the html code of the image to an empty string (l. 143 of the attached image).
![post-thumbnail-template](https://cloud.githubusercontent.com/assets/14749410/10015543/1f49df9e-6121-11e5-9fdf-10d6649d2c13.png)

As post thumbnail achievement is not found, the default image of the achievement type is returned.

Thank you in advance for your help,
The Glanum Agency.

**Comment by tw2113** [comment]
Good day @agence-glanum. Do you think you could start a new thread over at https://wordpress.org/support/plugin/badgeos with this? We try to leave GitHub issues for confirmed bugs and enhancement ideas, while utilizing the support forums for support requests.

To help get started, when you start the thread, if you could also provide where you're seeing the persistent old achievement images, it'll help expedite any necessary debugging.

As an example, if you also have BuddyPress and earned achievements being posted to activity streams, those aren't going to be dynamically updated because of how BuddyPress stores activity item content, including complete image urls.
