### ISSUE TITLE
include nominated by in the log

### ISSUE THREAD

**Issue by armtatoo** [opencredit/badgeos#510]
I need your help guys. 
I just used the plugin recently and purchased the leaderboard plugin and the report plugin however I am not happy with the limitation of all.
I don't have any coding experience unfortunately 
I need the nomination to be available for viewing once submitted and approved showing the name of issuer, the nominee and the content for nomination.
Also is there a way to display the name of issuers/nominated by for the issued achievement along with the nominated person in the entries log or any where else.
Thanks for the help.

**Comment by tw2113** [comment]
We have filters in place for these spots, but you are going to need someone with WordPress/hook experience to customize. I'd have someone check the content-filters.php file for a reference.

Since this is not an issue with the code itself, and more general support, I have to close the issue. For further support based requests, please use http://wordpress.org/support/plugin/badgeos
