### ISSUE TITLE
Badge pages (category and single post)

### ISSUE THREAD

**Issue by cbier** [opencredit/badgeos#512]
It seems like the badges are being treated as posts, so when i go to www.mydomain.com/badges it shows a category page (content-archive.php) and then I go to www.mydomain.com/badges/integrate-badgeos/ a single post (content-single.php).

How do I change these? On my site the archive and single post pages are not suitable for badges.

I would be happy to make a page to list all of the badges and a page to list a single badge, but I can't have it use the regular content-archive and content-single files

**Comment by tw2113** [comment]
All achievement types get registered as post types, and achievements in the types are essentially single posts in the associated post type. So that behavior is to be expected.

You should be able to customize as necessary with custom template files, single-badges.php would be used for single badge posts, archive-badges.php would handle the archive, if I recall right. Then you could display them all however you want with those specific templates. Not sure how much theming and template manipulation experience you have though.

Closing as it's not an actual issue with the code, just questions of how things are handled.

**Comment by cbier** [comment]
Thank you so much for the reply. I will try this

**Comment by tw2113** [comment]
Welcome.

If you have any other questions, we have the WordPress.org forums set up and actively monitored. You can find them at http://wordpress.org/support/plugin/badgeos

**Comment by cbier** [comment]
Thanks man! For others looking for documentation on this: http://codex.wordpress.org/Post_Type_Templates
