### ISSUE TITLE
Some translation issues (pt-BR)

### ISSUE THREAD

**Issue by gthron** [opencredit/badgeos#522]
Hello,

I'm building a WP website in brazilian-portuguese. I've already translated all sentences on the .pot file but still noticed some issues:

1. On the User's achievements page I'm using the shortcode [badgeos_achievements_list], all is fine but the "Show Details" at the right corner keeps reverting to the original english wording. At first it shows the pt-BR wording just fine "Exibir Detalhes", but when you press the down arrow and the up again it reverts to "Show Details". Take a look at the screenshots: https://imgur.com/DjmtEqb

2. I couldn't find the "Hide Details" words on the .pot file for translation.

3. The sentence "X Required Step(s)" is constructed in a different way in portuguese.
In portuguese it is "X Passo(s) Necessário(s)" where Passo(s) = Step(s) and Necessário(s) = Required, we invert the verb (to require) and the substantive (step). Instead of translating word by word it would be great to have the possibility of full sentence translation.

Some of my users are confused by the English words mixed with portuguese on their achievement page.

I can send you my pt-BR .po file if you want to include it on the BadgeOS languages folder, just let me know.

Thanks for this great plugin,
Gustavo Thron

**Comment by tw2113** [comment]
1. This is actually fixed in the alpha branch, but it's probably best to not use the alpha branch at the moment in a production site. I can't guarantee things will work flawlessly at the moment. If desired, I can help provide a copy the production-ready release that has the specific changes in place so you could utilize right now.

2. See Item 1 above.

3. Is this one for the frontend listing? or for the metabox in the admin area? Both spots have a filter you could use, instead of just the locatization method. That filter would allow you to list it however you want, and in whichever language you choose. Do note you'd need to be familiar with WordPress hooks to utilize that one.

For reference:
```
$output .= '<h4>' . apply_filters( 'badgeos_steps_heading', sprintf( __( '%1$d Required %2$s', 'badgeos' ), $count, $post_type_object->labels->name ), $steps ) . '</h4>';
```
```
add_meta_box( 'badgeos_steps_ui', apply_filters( 'badgeos_steps_ui_title', __( 'Required Steps', 'badgeos' ) ), 'badgeos_steps_ui_meta_box', $achievement_type, 'advanced', 'high' );
```

**Comment by gthron** [comment]
Hi,

1 & 2. I think I'll wait for the proper update release before updating BadgeOS in my website.
3. I've solved the problem inverting the meaning of the two words in the .po file. My php and wordpress knowledge are very basic (just enough to call variables here and there and replacing small stuff on some plugin code, translation related mostly), I do not feel confident to tinker with the code on this level. I just wanted BadgeOS to have an user friendly way to set this up.

Thanks for the prompt reply.

**Comment by tw2113** [comment]
Welcome. Since all the issues are already taken care of, I'm going to close this issue.
